create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text,
  project_type text not null,
  budget text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'contacted', 'completed')),
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

-- The backend uses the Supabase service-role key server-side.
-- No public SELECT/INSERT policies are required for this contact form.
-- Never put SUPABASE_SERVICE_ROLE_KEY in the React client.
alter table public.inquiries
add column if not exists timeline text;